// Auto-generated route configuration
// This file is automatically generated by the route-generator plugin
// Do not edit manually - your changes will be overwritten

import Route2 from '../contents/deployment/cloudflare-pages.mdx'
import Route3 from '../contents/deployment/docker.mdx'
import Route4 from '../contents/deployment/github-action.mdx'
import Route5 from '../contents/deployment/github-pages.mdx'
import Route1 from '../contents/deployment/index.mdx'
import Route6 from '../contents/deployment/vercel.mdx'
import Route7 from '../contents/docs-site.mdx'
import Route0 from '../contents/index.mdx'
import Route8 from '../contents/storage/index.mdx'

export interface RouteConfig {
  path: string
  component: React.ComponentType
  title: string
  meta: Record<string, unknown>
}

export const routes: RouteConfig[] = [
  {
    path: '/',
    component: Route0,
    title: 'Overview',
    meta: {
      title: 'Overview',
      description: "Project overview for Jacky's Photography, a customized Afilmory-powered photo gallery.",
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2026-04-26T00:00:00+01:00',
    },
  },
  {
    path: '/deployment',
    component: Route1,
    title: 'Deployment',
    meta: {
      title: 'Deployment',
      description: "Guide to deploying Jacky's Photography in production environments.",
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2026-04-26T00:00:00+01:00',
    },
  },
  {
    path: '/deployment/cloudflare-pages',
    component: Route2,
    title: 'Cloudflare Pages',
    meta: {
      title: 'Cloudflare Pages',
      description: "Guide to deploying Jacky's Photography via Cloudflare Pages.",
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2026-04-26T00:00:00+01:00',
    },
  },
  {
    path: '/deployment/docker',
    component: Route3,
    title: 'Docker',
    meta: {
      title: 'Docker',
      description: 'Guide to deploying Afilmory via Docker.',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-11-17T00:12:25+08:00',
    },
  },
  {
    path: '/deployment/github-action',
    component: Route4,
    title: 'GitHub Action',
    meta: {
      title: 'GitHub Action',
      description: "Guide to the GitHub Actions deployment workflow used by Jacky's Photography.",
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2026-04-26T00:00:00+01:00',
    },
  },
  {
    path: '/deployment/github-pages',
    component: Route5,
    title: 'GitHub Pages',
    meta: {
      title: 'GitHub Pages',
      description: "Guide to deploying Jacky's Photography via GitHub Pages.",
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2026-04-26T00:00:00+01:00',
    },
  },
  {
    path: '/deployment/vercel',
    component: Route6,
    title: 'Vercel',
    meta: {
      title: 'Vercel',
      description: "Guide to deploying Jacky's Photography via Vercel.",
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2026-04-26T00:00:00+01:00',
    },
  },
  {
    path: '/docs-site',
    component: Route7,
    title: 'Docs site',
    meta: {
      title: 'Docs site',
      description: 'Docs site introduction and contribution guide',
      createdAt: '2025-09-11T17:05:55+08:00',
      lastModified: '2025-09-11T17:10:35+08:00',
    },
  },
  {
    path: '/storage',
    component: Route8,
    title: 'Storage providers',
    meta: {
      title: 'Storage providers',
      description:
        'Afilmory can work with multiple storage providers, including local file system, S3, GitHub, and Eagle',
      createdAt: '2025-08-12T15:09:08+08:00',
      lastModified: '2026-04-26T00:00:00+01:00',
    },
  },
]

export default routes
