// Auto-generated route configuration
// This file is automatically generated by the route-generator plugin
// Do not edit manually - your changes will be overwritten

import Route1 from '../contents/accessibility/index.mdx'
import Route2 from '../contents/architecture/index.mdx'
import Route4 from '../contents/deployment/github-action.mdx'
import Route5 from '../contents/deployment/github-pages.mdx'
import Route3 from '../contents/deployment/index.mdx'
import Route6 from '../contents/deployment/vercel-preview.mdx'
import Route7 from '../contents/docs-site.mdx'
import Route0 from '../contents/index.mdx'
import Route8 from '../contents/performance/index.mdx'
import Route9 from '../contents/photo-metadata/index.mdx'
import Route10 from '../contents/storage/index.mdx'

export interface RouteConfig {
  path: string
  component: React.ComponentType
  title: string
  meta: Record<string, unknown>
}

export const routes: RouteConfig[] = [
  {
    path: '/',
    component: Route0,
    title: 'Overview',
    meta: {
      title: 'Overview',
      description: "Task-oriented documentation for developing, maintaining, and deploying Jacky's Photography.",
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2026-08-30T14:12:33+08:00',
    },
  },
  {
    path: '/accessibility',
    component: Route1,
    title: 'Interaction and Accessibility',
    meta: {
      title: 'Interaction and Accessibility',
      description:
        "Keyboard navigation, focus behavior, sharing fallbacks, and production data-visibility boundaries in Jacky's Photography.",
      createdAt: '2026-08-04T01:03:59+08:00',
      lastModified: '2026-08-29T14:01:43+08:00',
    },
  },
  {
    path: '/architecture',
    component: Route2,
    title: 'Architecture',
    meta: {
      title: 'Architecture',
      description:
        "Workspace responsibilities, dependency boundaries, generated data flow, and deployment shape for Jacky's Photography.",
      createdAt: '2026-08-30T13:22:42+08:00',
      lastModified: '2026-08-30T14:06:15+08:00',
    },
  },
  {
    path: '/deployment',
    component: Route3,
    title: 'Deployment',
    meta: {
      title: 'Deployment',
      description: "Guide to deploying Jacky's Photography in production environments.",
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2026-08-04T01:09:34+08:00',
    },
  },
  {
    path: '/deployment/github-action',
    component: Route4,
    title: 'GitHub Action',
    meta: {
      title: 'GitHub Action',
      description: "Current GitHub Actions validation and deployment workflow for Jacky's Photography.",
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2026-08-04T01:09:34+08:00',
    },
  },
  {
    path: '/deployment/github-pages',
    component: Route5,
    title: 'GitHub Pages Removal',
    meta: {
      title: 'GitHub Pages Removal',
      description: "Historical notes for the removed GitHub Pages deployment in Jacky's Photography.",
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2026-06-25T01:07:09+08:00',
    },
  },
  {
    path: '/deployment/vercel-preview',
    component: Route6,
    title: 'Vercel Preview',
    meta: {
      title: 'Vercel Preview',
      description: 'Guide to Vercel Preview deployments that pull the private photo repository during the build.',
      createdAt: '2026-05-13T22:45:00+08:00',
      lastModified: '2026-06-25T01:07:09+08:00',
    },
  },
  {
    path: '/docs-site',
    component: Route7,
    title: 'Docs site',
    meta: {
      title: 'Docs site',
      description: "How to maintain and publish the Jacky's Photography documentation site at docs.photo.jackyw.cn.",
      createdAt: '2025-09-11T17:05:55+08:00',
      lastModified: '2026-08-30T14:06:15+08:00',
    },
  },
  {
    path: '/performance',
    component: Route8,
    title: 'Performance',
    meta: {
      title: 'Performance',
      description: "Mobile-first loading and image performance notes for Jacky's Photography.",
      createdAt: '2026-04-27T00:00:00+01:00',
      lastModified: '2026-08-30T22:44:09+08:00',
    },
  },
  {
    path: '/photo-metadata',
    component: Route9,
    title: 'Photo Metadata',
    meta: {
      title: 'Photo Metadata',
      description: 'Manual photo descriptions, tags, manifest merge behavior, and SEO metadata workflow.',
      createdAt: '2026-05-09T00:00:00+01:00',
      lastModified: '2026-08-04T01:09:34+08:00',
    },
  },
  {
    path: '/storage',
    component: Route10,
    title: 'Storage providers',
    meta: {
      title: 'Storage providers',
      description: "Current storage-provider setup and supported alternatives for Jacky's Photography.",
      createdAt: '2025-08-12T15:09:08+08:00',
      lastModified: '2026-08-04T01:09:34+08:00',
    },
  },
]

export default routes
