// This file is automatically generated by the toc-extractor plugin
// Do not edit manually

export interface TocItem {
  id: string
  level: number
  text: string
  children?: TocItem[]
}

export interface FileToc {
  file: string
  path: string
  title: string
  toc: TocItem[]
}

export const tocData: FileToc[] = [
  {
    file: 'index.mdx',
    path: '/',
    title: 'Overview',
    toc: [
      {
        id: 'heading-jackys-photography',
        level: 1,
        text: "Jacky's Photography",
        children: [
          {
            id: 'heading-choose-a-task',
            level: 2,
            text: 'Choose a Task',
            children: [
              {
                id: 'heading-understand-the-system',
                level: 3,
                text: 'Understand the System',
                children: [],
              },
              {
                id: 'heading-maintain-photos-and-metadata',
                level: 3,
                text: 'Maintain Photos and Metadata',
                children: [],
              },
              {
                id: 'heading-build-and-deploy',
                level: 3,
                text: 'Build and Deploy',
                children: [],
              },
              {
                id: 'heading-contribute-or-maintain-docs',
                level: 3,
                text: 'Contribute or Maintain Docs',
                children: [],
              },
            ],
          },
          {
            id: 'heading-essential-workflow',
            level: 2,
            text: 'Essential Workflow',
            children: [],
          },
          {
            id: 'heading-public-links',
            level: 2,
            text: 'Public Links',
            children: [],
          },
          {
            id: 'heading-license-boundary',
            level: 2,
            text: 'License Boundary',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'accessibility/index.mdx',
    path: '/accessibility',
    title: 'Interaction and Accessibility',
    toc: [
      {
        id: 'heading-interaction-and-accessibility',
        level: 1,
        text: 'Interaction and Accessibility',
        children: [
          {
            id: 'heading-entering-keyboard-navigation',
            level: 2,
            text: 'Entering Keyboard Navigation',
            children: [],
          },
          {
            id: 'heading-header-controls',
            level: 2,
            text: 'Header Controls',
            children: [],
          },
          {
            id: 'heading-masonry-photo-navigation',
            level: 2,
            text: 'Masonry Photo Navigation',
            children: [],
          },
          {
            id: 'heading-dialog-focus',
            level: 2,
            text: 'Dialog Focus',
            children: [],
          },
          {
            id: 'heading-instagram-sharing',
            level: 2,
            text: 'Instagram Sharing',
            children: [],
          },
          {
            id: 'heading-map-summary',
            level: 2,
            text: 'Map Summary',
            children: [],
          },
          {
            id: 'heading-manifest-visibility',
            level: 2,
            text: 'Manifest Visibility',
            children: [],
          },
          {
            id: 'heading-automated-coverage',
            level: 2,
            text: 'Automated Coverage',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'architecture/index.mdx',
    path: '/architecture',
    title: 'Architecture',
    toc: [
      {
        id: 'heading-architecture',
        level: 1,
        text: 'Architecture',
        children: [
          {
            id: 'heading-runtime-shape',
            level: 2,
            text: 'Runtime Shape',
            children: [],
          },
          {
            id: 'heading-workspace-ownership',
            level: 2,
            text: 'Workspace Ownership',
            children: [],
          },
          {
            id: 'heading-photo-data-flow',
            level: 2,
            text: 'Photo Data Flow',
            children: [],
          },
          {
            id: 'heading-storage-and-publication',
            level: 2,
            text: 'Storage and Publication',
            children: [],
          },
          {
            id: 'heading-build-boundaries',
            level: 2,
            text: 'Build Boundaries',
            children: [],
          },
          {
            id: 'heading-dependency-rules',
            level: 2,
            text: 'Dependency Rules',
            children: [],
          },
          {
            id: 'heading-change-guide',
            level: 2,
            text: 'Change Guide',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'deployment/index.mdx',
    path: '/deployment',
    title: 'Deployment',
    toc: [
      {
        id: 'heading-deployment',
        level: 1,
        text: 'Deployment',
        children: [],
      },
    ],
  },
  {
    file: 'deployment/github-action.mdx',
    path: '/deployment/github-action',
    title: 'GitHub Action',
    toc: [
      {
        id: 'heading-github-action-deployment',
        level: 1,
        text: 'GitHub Action Deployment',
        children: [
          {
            id: 'heading-triggers',
            level: 2,
            text: 'Triggers',
            children: [],
          },
          {
            id: 'heading-pull-request-validation',
            level: 2,
            text: 'Pull-Request Validation',
            children: [],
          },
          {
            id: 'heading-production-validation',
            level: 2,
            text: 'Production Validation',
            children: [],
          },
          {
            id: 'heading-deployment-only-steps',
            level: 2,
            text: 'Deployment-Only Steps',
            children: [],
          },
          {
            id: 'heading-required-secrets',
            level: 2,
            text: 'Required Secrets',
            children: [],
          },
          {
            id: 'heading-cloudflare-r2-sync',
            level: 2,
            text: 'Cloudflare R2 Sync',
            children: [],
          },
          {
            id: 'heading-permissions',
            level: 2,
            text: 'Permissions',
            children: [],
          },
          {
            id: 'heading-output-targets',
            level: 2,
            text: 'Output Targets',
            children: [],
          },
          {
            id: 'heading-notes',
            level: 2,
            text: 'Notes',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'deployment/github-pages.mdx',
    path: '/deployment/github-pages',
    title: 'GitHub Pages Removal',
    toc: [
      {
        id: 'heading-github-pages-deployment-removed',
        level: 1,
        text: 'GitHub Pages Deployment Removed',
        children: [
          {
            id: 'heading-removed-automation',
            level: 2,
            text: 'Removed Automation',
            children: [],
          },
          {
            id: 'heading-local-build-equivalent',
            level: 2,
            text: 'Local Build Equivalent',
            children: [],
          },
          {
            id: 'heading-current-workflow-output',
            level: 2,
            text: 'Current Workflow Output',
            children: [],
          },
          {
            id: 'heading-if-re-enabling-pages',
            level: 2,
            text: 'If Re-Enabling Pages',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'deployment/vercel-preview.mdx',
    path: '/deployment/vercel-preview',
    title: 'Vercel Preview',
    toc: [
      {
        id: 'heading-vercel-preview-deployment',
        level: 1,
        text: 'Vercel Preview Deployment',
        children: [
          {
            id: 'heading-repository-configuration',
            level: 2,
            text: 'Repository Configuration',
            children: [],
          },
          {
            id: 'heading-environment-variables',
            level: 2,
            text: 'Environment Variables',
            children: [],
          },
          {
            id: 'heading-behavior',
            level: 2,
            text: 'Behavior',
            children: [],
          },
          {
            id: 'heading-pull-request-safety',
            level: 2,
            text: 'Pull Request Safety',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'docs-site.mdx',
    path: '/docs-site',
    title: 'Docs site',
    toc: [
      {
        id: 'heading-docs-site',
        level: 1,
        text: 'Docs Site',
        children: [
          {
            id: 'heading-public-urls',
            level: 2,
            text: 'Public URLs',
            children: [],
          },
          {
            id: 'heading-content-structure',
            level: 2,
            text: 'Content Structure',
            children: [],
          },
          {
            id: 'heading-commands',
            level: 2,
            text: 'Commands',
            children: [],
          },
          {
            id: 'heading-writing-pages',
            level: 2,
            text: 'Writing Pages',
            children: [],
          },
          {
            id: 'heading-style-notes',
            level: 2,
            text: 'Style Notes',
            children: [],
          },
          {
            id: 'heading-verification',
            level: 2,
            text: 'Verification',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'performance/index.mdx',
    path: '/performance',
    title: 'Performance',
    toc: [
      {
        id: 'heading-performance',
        level: 1,
        text: 'Performance',
        children: [
          {
            id: 'heading-image-pipeline',
            level: 2,
            text: 'Image Pipeline',
            children: [],
          },
          {
            id: 'heading-gallery-loading',
            level: 2,
            text: 'Gallery Loading',
            children: [],
          },
          {
            id: 'heading-manifest-loading',
            level: 2,
            text: 'Manifest Loading',
            children: [],
          },
          {
            id: 'heading-static-photo-metadata',
            level: 2,
            text: 'Static Photo Metadata',
            children: [],
          },
          {
            id: 'heading-javascript-loading',
            level: 2,
            text: 'JavaScript Loading',
            children: [],
          },
          {
            id: 'heading-regeneration',
            level: 2,
            text: 'Regeneration',
            children: [],
          },
          {
            id: 'heading-validation-checklist',
            level: 2,
            text: 'Validation Checklist',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'photo-metadata/index.mdx',
    path: '/photo-metadata',
    title: 'Photo Metadata',
    toc: [
      {
        id: 'heading-photo-metadata',
        level: 1,
        text: 'Photo Metadata',
        children: [
          {
            id: 'heading-sidecar-shape',
            level: 2,
            text: 'Sidecar Shape',
            children: [],
          },
          {
            id: 'heading-sync-workflow',
            level: 2,
            text: 'Sync Workflow',
            children: [],
          },
          {
            id: 'heading-manifest-merge',
            level: 2,
            text: 'Manifest Merge',
            children: [],
          },
          {
            id: 'heading-location-privacy',
            level: 2,
            text: 'Location Privacy',
            children: [],
          },
          {
            id: 'heading-frontend-usage',
            level: 2,
            text: 'Frontend Usage',
            children: [],
          },
          {
            id: 'heading-seo-output',
            level: 2,
            text: 'SEO Output',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'storage/index.mdx',
    path: '/storage',
    title: 'Storage providers',
    toc: [
      {
        id: 'heading-storage-providers',
        level: 1,
        text: 'Storage Providers',
        children: [
          {
            id: 'heading-current-setup',
            level: 2,
            text: 'Current Setup',
            children: [],
          },
          {
            id: 'heading-manifest-and-thumbnails',
            level: 2,
            text: 'Manifest And Thumbnails',
            children: [],
          },
          {
            id: 'heading-cloudflare-r2-layout',
            level: 2,
            text: 'Cloudflare R2 Layout',
            children: [],
          },
          {
            id: 'heading-supported-providers',
            level: 2,
            text: 'Supported Providers',
            children: [
              {
                id: 'heading-local',
                level: 3,
                text: 'Local',
                children: [],
              },
              {
                id: 'heading-s3-compatible',
                level: 3,
                text: 'S3-Compatible',
                children: [],
              },
              {
                id: 'heading-github',
                level: 3,
                text: 'GitHub',
                children: [],
              },
              {
                id: 'heading-eagle',
                level: 3,
                text: 'Eagle',
                children: [],
              },
            ],
          },
          {
            id: 'heading-processing-pipeline',
            level: 2,
            text: 'Processing Pipeline',
            children: [],
          },
          {
            id: 'heading-provider-comparison',
            level: 2,
            text: 'Provider Comparison',
            children: [],
          },
          {
            id: 'heading-security-notes',
            level: 2,
            text: 'Security Notes',
            children: [],
          },
        ],
      },
    ],
  },
]

// Helper function to find TOC data by route path
export function getTocByPath(routePath: string): TocItem[] | undefined {
  const item = tocData.find((item) => item.path === routePath)
  return item?.toc
}
