// This file is automatically generated by the toc-extractor plugin
// Do not edit manually

export interface TocItem {
  id: string
  level: number
  text: string
  children?: TocItem[]
}

export interface FileToc {
  file: string
  path: string
  title: string
  toc: TocItem[]
}

export const tocData: FileToc[] = [
  {
    file: 'index.mdx',
    path: '/',
    title: 'Overview',
    toc: [
      {
        id: 'heading-jackys-photography',
        level: 1,
        text: "Jacky's Photography",
        children: [
          {
            id: 'heading-what-it-builds',
            level: 2,
            text: 'What It Builds',
            children: [],
          },
          {
            id: 'heading-repository-layout',
            level: 2,
            text: 'Repository Layout',
            children: [],
          },
          {
            id: 'heading-storage-providers',
            level: 2,
            text: 'Storage Providers',
            children: [],
          },
          {
            id: 'heading-development',
            level: 2,
            text: 'Development',
            children: [],
          },
          {
            id: 'heading-photo-workflow',
            level: 2,
            text: 'Photo Workflow',
            children: [],
          },
          {
            id: 'heading-deployment',
            level: 2,
            text: 'Deployment',
            children: [],
          },
          {
            id: 'heading-license',
            level: 2,
            text: 'License',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'deployment/index.mdx',
    path: '/deployment',
    title: 'Deployment',
    toc: [
      {
        id: 'heading-deployment',
        level: 1,
        text: 'Deployment',
        children: [],
      },
    ],
  },
  {
    file: 'deployment/github-action.mdx',
    path: '/deployment/github-action',
    title: 'GitHub Action',
    toc: [
      {
        id: 'heading-github-action-deployment',
        level: 1,
        text: 'GitHub Action Deployment',
        children: [
          {
            id: 'heading-jobs',
            level: 2,
            text: 'Jobs',
            children: [],
          },
          {
            id: 'heading-build-steps',
            level: 2,
            text: 'Build Steps',
            children: [],
          },
          {
            id: 'heading-permissions',
            level: 2,
            text: 'Permissions',
            children: [],
          },
          {
            id: 'heading-output-targets',
            level: 2,
            text: 'Output Targets',
            children: [],
          },
          {
            id: 'heading-notes',
            level: 2,
            text: 'Notes',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'deployment/github-pages.mdx',
    path: '/deployment/github-pages',
    title: 'GitHub Pages',
    toc: [
      {
        id: 'heading-github-pages-deployment',
        level: 1,
        text: 'GitHub Pages Deployment',
        children: [
          {
            id: 'heading-repository-settings',
            level: 2,
            text: 'Repository Settings',
            children: [],
          },
          {
            id: 'heading-local-build-equivalent',
            level: 2,
            text: 'Local Build Equivalent',
            children: [],
          },
          {
            id: 'heading-workflow-output',
            level: 2,
            text: 'Workflow Output',
            children: [],
          },
          {
            id: 'heading-custom-domain',
            level: 2,
            text: 'Custom Domain',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'docs-site.mdx',
    path: '/docs-site',
    title: 'Docs site',
    toc: [
      {
        id: 'heading-docs-site',
        level: 1,
        text: 'Docs Site',
        children: [
          {
            id: 'heading-content-structure',
            level: 2,
            text: 'Content Structure',
            children: [],
          },
          {
            id: 'heading-commands',
            level: 2,
            text: 'Commands',
            children: [],
          },
          {
            id: 'heading-writing-pages',
            level: 2,
            text: 'Writing Pages',
            children: [],
          },
          {
            id: 'heading-style-notes',
            level: 2,
            text: 'Style Notes',
            children: [],
          },
          {
            id: 'heading-verification',
            level: 2,
            text: 'Verification',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'performance/index.mdx',
    path: '/performance',
    title: 'Performance',
    toc: [
      {
        id: 'heading-performance',
        level: 1,
        text: 'Performance',
        children: [
          {
            id: 'heading-image-pipeline',
            level: 2,
            text: 'Image Pipeline',
            children: [],
          },
          {
            id: 'heading-gallery-loading',
            level: 2,
            text: 'Gallery Loading',
            children: [],
          },
          {
            id: 'heading-manifest-loading',
            level: 2,
            text: 'Manifest Loading',
            children: [],
          },
          {
            id: 'heading-static-photo-metadata',
            level: 2,
            text: 'Static Photo Metadata',
            children: [],
          },
          {
            id: 'heading-javascript-loading',
            level: 2,
            text: 'JavaScript Loading',
            children: [],
          },
          {
            id: 'heading-regeneration',
            level: 2,
            text: 'Regeneration',
            children: [],
          },
          {
            id: 'heading-validation-checklist',
            level: 2,
            text: 'Validation Checklist',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'photo-metadata/index.mdx',
    path: '/photo-metadata',
    title: 'Photo Metadata',
    toc: [
      {
        id: 'heading-photo-metadata',
        level: 1,
        text: 'Photo Metadata',
        children: [
          {
            id: 'heading-sidecar-shape',
            level: 2,
            text: 'Sidecar Shape',
            children: [],
          },
          {
            id: 'heading-sync-workflow',
            level: 2,
            text: 'Sync Workflow',
            children: [],
          },
          {
            id: 'heading-manifest-merge',
            level: 2,
            text: 'Manifest Merge',
            children: [],
          },
          {
            id: 'heading-frontend-usage',
            level: 2,
            text: 'Frontend Usage',
            children: [],
          },
          {
            id: 'heading-seo-output',
            level: 2,
            text: 'SEO Output',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'storage/index.mdx',
    path: '/storage',
    title: 'Storage providers',
    toc: [
      {
        id: 'heading-storage-providers',
        level: 1,
        text: 'Storage Providers',
        children: [
          {
            id: 'heading-supported-providers',
            level: 2,
            text: 'Supported Providers',
            children: [
              {
                id: 'heading-s3-compatible-storage',
                level: 3,
                text: 'S3-Compatible Storage',
                children: [],
              },
              {
                id: 'heading-github-storage',
                level: 3,
                text: 'GitHub Storage',
                children: [],
              },
              {
                id: 'heading-eagle-storage',
                level: 3,
                text: 'Eagle Storage',
                children: [],
              },
              {
                id: 'heading-local-file-system',
                level: 3,
                text: 'Local File System',
                children: [],
              },
            ],
          },
          {
            id: 'heading-photo-processing-workflow',
            level: 2,
            text: 'Photo Processing Workflow',
            children: [
              {
                id: 'heading-image-processing-pipeline',
                level: 3,
                text: 'Image Processing Pipeline',
                children: [],
              },
              {
                id: 'heading-storage-organization',
                level: 3,
                text: 'Storage Organization',
                children: [],
              },
              {
                id: 'heading-processing-commands',
                level: 3,
                text: 'Processing Commands',
                children: [],
              },
            ],
          },
          {
            id: 'heading-environment-specific-configurations',
            level: 2,
            text: 'Environment-Specific Configurations',
            children: [
              {
                id: 'heading-development-setup',
                level: 3,
                text: 'Development Setup',
                children: [],
              },
              {
                id: 'heading-production-setup',
                level: 3,
                text: 'Production Setup',
                children: [],
              },
            ],
          },
          {
            id: 'heading-api-limitations',
            level: 2,
            text: 'API Limitations',
            children: [
              {
                id: 'heading-github-storage-limits',
                level: 3,
                text: 'GitHub Storage Limits',
                children: [],
              },
              {
                id: 'heading-storage-provider-comparison',
                level: 3,
                text: 'Storage Provider Comparison',
                children: [],
              },
            ],
          },
          {
            id: 'heading-security-considerations',
            level: 2,
            text: 'Security Considerations',
            children: [
              {
                id: 'heading-s3-bucket-policies',
                level: 3,
                text: 'S3 Bucket Policies',
                children: [],
              },
              {
                id: 'heading-github-repository-settings',
                level: 3,
                text: 'GitHub Repository Settings',
                children: [],
              },
              {
                id: 'heading-environment-variables',
                level: 3,
                text: 'Environment Variables',
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
]

// Helper function to find TOC data by file path
export function getTocByFile(filePath: string): TocItem[] | undefined {
  const item = tocData.find((item) => item.file === filePath)
  return item?.toc
}

// Helper function to find TOC data by route path
export function getTocByPath(routePath: string): TocItem[] | undefined {
  const item = tocData.find((item) => item.path === routePath)
  return item?.toc
}

// Helper function to flatten TOC tree into a simple array
export function flattenToc(toc: TocItem[]): TocItem[] {
  const result: TocItem[] = []

  function traverse(items: TocItem[]) {
    for (const item of items) {
      result.push({
        id: item.id,
        level: item.level,
        text: item.text,
      })
      if (item.children && item.children.length > 0) {
        traverse(item.children)
      }
    }
  }

  traverse(toc)
  return result
}

// Helper function to get all headings at a specific level
export function getHeadingsByLevel(toc: TocItem[], level: number): TocItem[] {
  const result: TocItem[] = []

  function traverse(items: TocItem[]) {
    for (const item of items) {
      if (item.level === level) {
        result.push(item)
      }
      if (item.children && item.children.length > 0) {
        traverse(item.children)
      }
    }
  }

  traverse(toc)
  return result
}
