packages:
  - apps/web
  - packages/*
  - packages/*/*

catalog:
  '@egoist/tailwindcss-icons': 1.9.2
  '@iconify-json/mingcute': 1.2.7
  '@t3-oss/env-core': 0.13.11
  '@tailwindcss/postcss': 4.2.4
  '@tailwindcss/typography': 0.5.19
  dotenv-expand: 12.0.3
  tailwind-scrollbar: 4.0.2
  tailwind-variants: 3.2.2
  tailwindcss: 4.2.4
  tailwindcss-animate: 1.0.7
  tailwindcss-safe-area: 1.3.0
  tailwindcss-uikit-colors: 1.0.0
  typescript: 5.9.3
  zod: 4.4.2

onlyBuiltDependencies:
  - esbuild
  - puppeteer
